### ISSUE TITLE
intersectionRatio === 0 is not a safe assumption for "exit"

### ISSUE THREAD

**Issue by nolanlawson** [yoshuawuyts/on-intersect#2]
[This code](https://github.com/yoshuawuyts/on-intersect/blob/6b9b5b36f66ddd4dfb3aafca2797e731d6822ade/index.js#L40-L41) may lead to very subtle bugs because, per the spec, an element may still be "intersecting" even though `intersectionRatio` is 0. For instance, this situation is possible:

```js
{
  isIntersecting: true,
  intersectionRatio: 0
}
```

This is due to how edge adjacency works, and you can read the gory details here (https://github.com/w3c/IntersectionObserver/issues/222). You can repro this by scrolling such that the element perfectly overlaps the root (may be easiest to repro in Firefox currently).

My recommendation would be to change the `if()` statement to

```js
if (typeof entry.isIntersecting === 'boolean' ? !entry.isIntersecting : entry.intersectionRatio === 0) {
  onExit()
}
```

The case where `typeof entry.isIntersecting` isn't a boolean covers Edge 15, which does not support `isIntersecting`,  and where `entry.intersectionRatio === 0` is actually a safe proxy for "no longer intersecting."

**Comment by yoshuawuyts** [comment]
Thanks heaps! Reworked the API, and included this lil snip. Should be a lot better now! :sparkles:

📦 `v2.0.0`
